name: Build

on:
  check_run:
    types:
      - created
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn
      - run: yarn build
