name: Publish to NPM

on:
  workflow_run:
    workflows:
      - "Release"
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: yarn
      - run: yarn build
        continue-on-error: true
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - run: yarn publish --new-version=${{ steps.package-version.outputs.current-version}}
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
