name: Test

on:
  check_run:
    types:
      - created
  pull_request:
    types:
      - opened
      - reopened
      - edited
    branches:
      - develop
    tags-ignore:
      - v1.*

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code 🛎
        uses: actions/checkout@v2

      - name: Run Component tests 🧪
        uses: cypress-io/github-action@v2
        with:
          install: true
          command: yarn cypress run --component --record --key ${{secrets.CYPRESS_RECORD_KEY}} --browser electron --env networkMode=stub
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_dhis2BaseUrl: ${{ secrets.dhis2BaseUrl}}
          CYPRESS_dhis2Username: ${{ secrets.dhis2Username }}
          CYPRESS_dhis2Password: ${{ secrets.dhis2Password }}
          CYPRESS_dhis2ApiVersion: ${{ secrets.dhis2ApiVersion }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
